### ISSUE TITLE
Proposal - SASS usage

### ISSUE THREAD

**Issue by Thielo** [MarcoHengstenberg/forthehorde#1]
Cryptic Issue Title ftw ;)  

for a uncertain user, like me, who switches between SASS and LESS all the time, it would be great to use SASS in this "Toolkit" (is it a toolkit btw?)

Sure, adding the following piece of code to the **package.json**, does the magic of _"now you can use SASS, you foolish dude"_

```
"grunt-contrib-sass"    : "*",
```

But there is still many other things to ensure the change to SASS from LESS in the **gruntfile.js**.
I would create a Pull Request, but I´m not that into Grunt right now.

**Step 1: Adding Variables to the gruntfile.js**

```
var globalConfig = {
    styleFilesFolder: 'less',
    styleTaskNamePrefix: 'lessy'
};
```

**Step 2: Using these variables in the gruntfile.js**
This is, where I need your competence. Because if have no clue, if stuff like the following works.

```
atf: {
            files: [globalConfig.styleFilesFolder+'/atf/*.less'],
            tasks: [globalConfig.styleTaskNamePrefix+'/-atf']
},
```

**Step 3: ..**

**Step 4: Profit!**
All (especially me) are happy ;)

---

Or would it be a better idea, just to create a second "functions"-block, just for the sass part, and do it the "make the code bigger"-dance ;)

**Comment by MarcoHengstenberg** [comment]
_"My Richard brings all the preprocessors to the yard."_
**\- Kelis, 2003, Song: "Preprocessor"**

Well, yes and no, in order to add Sass I'd simply add the Grunttask to the package.json and to the gruntfile but comment it out. That way LESS would be default but you could always switch by changing the commenting and then do the `npm install` afterwards.
Apart from that the setup would be pretty much the same with Sass as with LESS I suppose. I also think of adding a little Stylus to the build, while I'm at it.

I'll have a look at this when I got a little more time on my hands. Thanks for the suggestion!

PostCSS would be another option but I'm not ready for this. =D

**Comment by Thielo** [comment]
Yeah, I have the same "problem" with PostCSS :+1: 

In the end, SASS and LESS are the same with a slightly different Syntax... SameSS :D

**Comment by MarcoHengstenberg** [comment]
Sooo, I've added a note for people who are into other preprocessors.
I would make a bad job at explaining how to switch between the prepros and on top it is not a good idea to add comments to the `package.json` file from my experience (as it refused to do it's job entirely after I added comments).

Note is at the end of this block: [LESStoCSS](https://github.com/MarcoHengstenberg/forthehorde#lesstocss)

**Comment by MarcoHengstenberg** [comment]
Errr. @Thielo is this issue solved for you then?
