### ISSUE TITLE
Proposal - Extending the html-blocks

### ISSUE THREAD

**Issue by Thielo** [MarcoHengstenberg/forthehorde#2]
Is it possible to extend the htmlmin/htmlhint Function-Blocks, so they do not only _.html_ files, but also _.php_ files, laying in _unminified-html_ folder.

Because, i plan to create a simple include in the header, to include the atf-styling right there.

**Comment by MarcoHengstenberg** [comment]
About HTMLhint:

> HTMLHint is a Static Code Analysis Tool for HTML, you can use it with IDE or in build system.

So, no, unfortunately you would have to use something else in order to go with _.php_ files.
I'll have a look into this Grunttask as soon as I got the time: https://github.com/bezoerb/grunt-php2html
Looks promising from the first glance – it comes with a hinting block as it seems:
https://github.com/bezoerb/grunt-php2html#options

**Comment by MarcoHengstenberg** [comment]
Shutting down the issue, now.
Might open a new task when I'll have had a deeper look on the php2html task I mentioned in the comment earlier.
